// Generates docs/cli.md from the CLI's command tree, the same data `dispatch commands` prints.
// Run: pnpm exec tsx scripts/cli-docs.ts
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { tree, type Node } from "../apps/cli/src/lib/tree.js";
import { program } from "../apps/cli/src/program.js";

const intro = `# CLI

This file is generated by \`scripts/cli-docs.ts\` from \`dispatch commands\`. Edit the command definitions in \`apps/cli/src/commands\`, then run \`pnpm exec tsx scripts/cli-docs.ts\`.

The CLI is named \`dispatch\` in the examples. During local development, run it through pnpm:

\`\`\`sh
pnpm --filter @dispatchmail/cli start -- doctor
\`\`\`

Command names follow the Resend CLI, so most scripts written for \`resend\` work after replacing the binary name.

## Credentials

\`dispatch login\` asks for an API URL and a key, checks the pair with \`GET /me\`, and saves it as a profile in \`~/.config/dispatch/credentials.json\` with mode 0600. A profile is a URL plus a key, because every Dispatch install has its own host. \`dispatch auth list\` shows the saved profiles and \`dispatch auth switch <name>\` changes the active one.

A saved key is only sent to the URL it was saved with. Each command picks its key and URL like this:

1. \`--profile\` or \`DISPATCH_PROFILE\` uses that profile's key and URL and ignores \`DISPATCH_API_KEY\` and \`DISPATCH_API_URL\`. Adding \`--api-url\` for another host fails with \`auth_error\` unless \`--api-key\` is given too.
2. \`--api-key\`, then \`DISPATCH_API_KEY\`, go to the URL from \`--api-url\`, then \`DISPATCH_API_URL\`, then the active profile, then \`http://localhost:3100\`.
3. With no key from a flag or the environment, the active profile is used, unless \`--api-url\` or \`DISPATCH_API_URL\` names another host. In that case the command fails with \`auth_error\` and the saved key stays where it is.
4. When the URL is \`localhost\` or \`127.0.0.1\` and no key is set, the CLI uses the seeded dev key, so \`pnpm run doctor\` works right after \`pnpm db:seed\`.

The CLI loads \`.env\` from the working directory, and then the one at the root of this repository when it runs inside it. \`API_URL\` in those files or in the environment is read only when it names this machine, because many unrelated projects define that name. Use \`DISPATCH_API_URL\` for a remote API. \`DISPATCH_BASE_URL\`, the name the SDKs read, works too.

\`dispatch open\` needs the dashboard's URL in \`DISPATCH_APP_URL\` or \`APP_URL\` when the API is not local. The credentials file lives under \`XDG_CONFIG_HOME\` when that is set, and under \`~/.config\` otherwise.

If the credentials file cannot be parsed, commands fail with \`credentials_error\` unless both \`--api-key\` and \`--api-url\` are given. \`dispatch login\` moves the broken file to \`credentials.json.unreadable\` and starts a new one.

\`dispatch whoami\` prints which URL, key, and profile a command would use. It reads the credentials file and makes no network call.

## Output and errors

On a terminal, lists print as tables and other commands print a short summary. When stdout is piped, or with \`--json\`, every command prints the API's JSON to stdout, so \`dispatch emails list | jq .data\` works. \`-q\` implies \`--json\` and also hides spinners and status lines, which go to stderr.

A failed command exits 1 and writes \`{"error":{"message","code","statusCode"}}\` to stderr in JSON mode, or \`Error: <message>\` on a terminal. The code is the API's error name when the API returned one, such as \`validation_error\` or \`not_found\`. Cancelling a prompt exits 130.

Requests that get a 429 are retried up to three times, waiting as long as \`Retry-After\` says.

## Prompts and confirmation

IDs are optional on most commands. On a terminal, a missing ID opens a picker and a missing required flag opens a prompt. Without a terminal, or with \`--json\`, the command fails with \`missing_id\` or \`missing_flags\` instead. Destructive commands ask for confirmation on a terminal and need \`--yes\` otherwise, or they fail with \`confirmation_required\`.

## Lists

List commands take \`--limit\` (1 to 100, default 10), \`--after <id>\`, and \`--before <id>\`. Passing both cursors fails with \`invalid_pagination\`. When more results exist, the table ends with the exact command for the next page. Most groups run \`list\` when called without a subcommand, so \`dispatch domains\` lists domains. Every \`list\` has the alias \`ls\` and every \`delete\` has the alias \`rm\`.

## Files and stdin

Flags that take a file, such as \`--html-file\`, \`--text-file\`, \`--file\`, and \`--attachments-file\`, read stdin when given \`-\`. Only one flag per command can read stdin.

\`--attachment\` takes a spec of the form \`path;cid=logo;type=image/png;filename=logo.png\`, where everything after the path is optional. A \`cid\` makes the file an inline image.

## React Email

\`--react-email <file.tsx>\` on \`emails send\`, \`emails batch\`, \`broadcasts create\`, \`broadcasts update\`, \`templates create\`, and \`templates update\` bundles the file with esbuild against your project's \`node_modules\`, renders it, and sends the HTML. \`--props <json>\` sets the component's props. Without it, \`emails send\` and \`emails batch\` use the component's \`PreviewProps\`, then \`{}\`. Templates and broadcasts are stored and filled in later, so without \`--props\` they keep a \`{{{KEY}}}\` placeholder for each declared variable, as \`templates push\` does for a file or a directory of files.

## Old command names

These names from earlier versions still work and are hidden from help. They will be removed in a later release.

| Old | Now |
|:---|:---|
| \`send\` | \`emails send\` |
| \`batch\` | \`emails batch\` |
| \`keys\` | \`api-keys\` |
| \`received\` | \`emails receiving\` |
| \`listen\` | \`webhooks listen\` |
| \`replay <webhook-id>\` | \`webhooks events replay <webhook-id>\` |
| \`test-webhook\` | \`webhooks test\` |
| \`verify-domain\` | \`domains doctor\` |
| \`webhooks attempts\` | \`webhooks events list\` |
| \`suppressions create\` | \`suppressions add\` |
| \`broadcasts clone\` | \`broadcasts duplicate\` |

Old flags such as \`--first\`, \`--last\`, \`--segment\`, \`--topic\`, \`--scope\`, and \`--variables\` are also accepted where they used to be.
`;

const cell = (text: string) => text.replace(/\|/g, "\\|");

function usage(node: Node, path: string[]) {
  const args = node.arguments.map((argument) => (argument.required ? `<${argument.name}>` : `[${argument.name}]`));
  const options = node.options.length ? ["[options]"] : [];
  return ["dispatch", ...path, ...args, ...options].join(" ");
}

function section(node: Node, path: string[], depth: number): string[] {
  const lines: string[] = [];
  const title = `dispatch ${path.join(" ")}`;
  lines.push(`${"#".repeat(Math.min(depth, 4))} \`${title}\``, "");
  if (node.aliases.length) lines.push(`${node.description}. Alias: ${node.aliases.map((alias) => `\`${alias}\``).join(", ")}.`, "");
  else lines.push(`${node.description}.`, "");

  if (node.subcommands.length) {
    lines.push("| Command | Description |", "|:---|:---|");
    for (const child of node.subcommands) {
      const names = [child.name, ...child.aliases].map((name) => `\`${name}\``).join(", ");
      lines.push(`| ${names} | ${cell(child.description)} |`);
    }
    lines.push("");
    for (const child of node.subcommands) lines.push(...section(child, [...path, child.name], depth + 1));
    return lines;
  }

  lines.push("```sh", usage(node, path), "```", "");
  if (node.arguments.length) {
    lines.push("| Argument | Description |", "|:---|:---|");
    for (const argument of node.arguments) lines.push(`| \`${argument.name}\` | ${cell(argument.description)}${argument.required ? "" : " (optional)"} |`);
    lines.push("");
  }
  if (node.options.length) {
    lines.push("| Option | Description |", "|:---|:---|");
    for (const option of node.options) {
      const extra = [
        option.choices ? `One of ${option.choices.map((choice) => `\`${choice}\``).join(", ")}.` : "",
        option.default !== undefined ? `Default \`${String(option.default)}\`.` : "",
      ]
        .filter(Boolean)
        .join(" ");
      lines.push(`| \`${cell(option.flags)}\` | ${cell(option.description)}${extra ? `. ${extra}` : ""} |`);
    }
    lines.push("");
  }
  return lines;
}

export function render(root: Node) {
  const lines = [intro, "## Global options", "", "| Option | Description |", "|:---|:---|"];
  for (const option of root.options) lines.push(`| \`${cell(option.flags)}\` | ${cell(option.description)} |`);
  lines.push("", "## Commands", "", "| Command | Description |", "|:---|:---|");
  for (const child of root.subcommands) lines.push(`| \`${child.name}\` | ${cell(child.description)} |`);
  lines.push("");
  for (const child of root.subcommands) lines.push(...section(child, [child.name], 3));
  return `${lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`;
}

const out = fileURLToPath(new URL("../docs/cli.md", import.meta.url));
writeFileSync(out, render(tree(program)));
console.log(`Wrote ${out}`);
